name: Build Executable
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Brew dependencies
        run: brew install p7zip coreutils
      - name: Build and Install
        run: |
          bun i
          bun run build
      - name: Compress executable
        run: |
          cp build/amdhelper .
          tar c ./amdhelper | ./gz99 amdhelper.gz
      - name: Publish release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./amdhelper.gz
          tag: ${{ inputs.tag }}
          name: AMDHelper ${{ inputs.tag }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
