name: Build Executable
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun run build
      - name: Publish release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./src/build/AMDHelper
          tag: ${{ inputs.tag }}
          name: AMDHelper ${{ inputs.tag }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}